service: slack-integration-slackbot
frameworkVersion: "4"

# ダッシュボード機能を無効化（AWS Profile使用）
console: false

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-northeast-1
  logRetentionInDays: 7
  stage: ${opt:stage, 'dev'}

custom:
  secrets: ${file(../config/secrets.yml)}

plugins:
  - serverless-iam-roles-per-function

functions:
  slackbot:
    name: slack-integration-slackbot-${self:provider.stage}-slackbot
    handler: bot.handler
    environment:
      DYNAMODB_TABLE: ${self:custom.secrets.DYNAMODB_TABLE}-${self:provider.stage}
      DYNAMODB_REGION: ${self:provider.region}
      SLACK_CLIENT_ID: ${self:custom.secrets.SLACK_CLIENT_ID}
      SLACK_CLIENT_SECRET: ${self:custom.secrets.SLACK_CLIENT_SECRET}
      SLACK_SIGNING_SECRET: ${self:custom.secrets.SLACK_SIGNING_SECRET}
      SLACK_STATE_SECRET: ${self:custom.secrets.SLACK_STATE_SECRET}
      SLACK_BOT_TOKEN: ${self:custom.secrets.SLACK_BOT_TOKEN}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
          - dynamodb:Query
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:DeleteItem
        Resource:
          - arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.secrets.DYNAMODB_TABLE}-${self:provider.stage}
    events:
      - http:
          path: slack/events
          method: post
          cors: true
