# Slack/AWS連携用シークレット設定ファイルの雛形
# 実際の値は各自の環境に合わせて入力してください

SLACK_CLIENT_ID: "your-slack-client-id"          # SlackアプリのClient ID
SLACK_CLIENT_SECRET: "your-slack-client-secret"  # SlackアプリのClient Secret
SLACK_SIGNING_SECRET: "your-slack-signing-secret" # SlackアプリのSigning Secret
SLACK_STATE_SECRET: "state-secret"               # SlackアプリのState Secret (CSRF対策などに利用)openssl rand -base64 32なので生成

SLACK_BOT_TOKEN: "xoxb-your-bot-token"           # Slack Bot Token
DYNAMODB_TABLE: "SlackIntegrations"              # DynamoDBテーブル名
SLACK_REDIRECT_URI: "https://example.com/slack/oauth/callback" # Slack OAuthのリダイレクトURI