version = 0.1

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "slack-integration-sam-prod"
s3_bucket = ""  # SAM will create a managed bucket
confirm_changeset = false  # 本番では自動実行
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "SlackClientId=YOUR_PROD_CLIENT_ID_HERE",
  "SlackClientSecret=YOUR_PROD_CLIENT_SECRET_HERE",
  "SlackSigningSecret=YOUR_PROD_SIGNING_SECRET_HERE",
  "SlackRedirectUri=https://YOUR_PROD_API_URL/slack/oauth/callback",
  "SlackStateSecret=YOUR_PROD_STATE_SECRET_HERE",
  "SlackBotToken=xoxb-YOUR_PROD_BOT_TOKEN_HERE",
  "DynamoDBTableName=SlackIntegrations-prod"
]
region = "ap-northeast-1"

[prod.local_start_api]
[prod.local_start_api.parameters]
host = "0.0.0.0"
port = 3000
