version = 0.1

[local]
[local.start_api]
[local.start_api.parameters]
host = "127.0.0.1"
port = 3000
parameter_overrides = [
  "SlackClientId=test-client-id",
  "SlackClientSecret=test-client-secret", 
  "SlackSigningSecret=test-signing-secret",
  "SlackRedirectUri=http://localhost:3000/slack/oauth/callback",
  "SlackStateSecret=test-state-secret",
  "SlackBotToken=xoxb-test-bot-token",
  "DynamoDBTableName=SlackIntegrations-local"
]

[local.start_lambda]
[local.start_lambda.parameters]
parameter_overrides = [
  "SlackClientId=test-client-id",
  "SlackClientSecret=test-client-secret",
  "SlackSigningSecret=test-signing-secret", 
  "SlackRedirectUri=http://localhost:3000/slack/oauth/callback",
  "SlackStateSecret=test-state-secret",
  "SlackBotToken=xoxb-test-bot-token",
  "DynamoDBTableName=SlackIntegrations-local"
]

[local.invoke]
[local.invoke.parameters]
parameter_overrides = [
  "SlackClientId=test-client-id",
  "SlackClientSecret=test-client-secret",
  "SlackSigningSecret=test-signing-secret",
  "SlackRedirectUri=http://localhost:3000/slack/oauth/callback", 
  "SlackStateSecret=test-state-secret",
  "SlackBotToken=xoxb-test-bot-token",
  "DynamoDBTableName=SlackIntegrations-local"
]
