# Slack Integration API設定ファイル (AWS SAM版)
# このファイルをコピーして secrets.yml を作成し、実際の値を設定してください

SLACK_CLIENT_ID: your_slack_client_id_here
SLACK_CLIENT_SECRET: your_slack_client_secret_here
SLACK_SIGNING_SECRET: your_slack_signing_secret_here
SLACK_REDIRECT_URI: https://your-api-gateway-url/slack/oauth/callback
SLACK_STATE_SECRET: your_slack_state_secret_here
SLACK_BOT_TOKEN: xoxb-your-bot-token-here
DYNAMODB_TABLE: SlackIntegrations
DYNAMODB_REGION: ap-northeast-1
